### ISSUE TITLE
how to run 'npm install' with android code

### ISSUE THREAD

**Issue by wtchaos** [janeasystems/nodejs-mobile-samples#14] opened 2018-12-26 03:09 UTC
I Embed the nodejs in my android native project，and deploy the nodejs project on android system, but   
I don‘t know how to install the node modules(run command in terminal?)，how can I solve it, thanks.

**Comment by jaimecbernardo** [comment] 2018-12-26 19:32
This is a duplicate of: https://github.com/janeasystems/nodejs-mobile/issues/155

**Closed by jaimecbernardo** 2018-12-26 19:32 UTC
