### ISSUE TITLE
Error while useing the app on android

### ISSUE THREAD

**Issue by heot0198** [JaneaSystems/nodejs-mobile-samples#29] opened 2020-07-08 12:24 UTC
The app works fine on an android emulator but crashes every time on the device

LOG:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yourorg.sample, PID: 11593
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_GetIP" referenced by "/data/app/com.yourorg.sample-I1bJqA_iGJ970nSzsBbQ8Q==/lib/arm64/libnode.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.yourorg.sample.MainActivity.loadLib(MainActivity.java:244)
        at com.yourorg.sample.MainActivity.onCreate(MainActivity.java:42)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/MQSEventManagerDelegate: failed to get MQSService.
I/Process: Sending signal. PID: 11593 SIG: 9
Application terminated.

**Comment by jaimecbernardo** [comment] 2020-07-13 19:23
Duplicate of: https://github.com/JaneaSystems/nodejs-mobile/issues/274

**Closed** 2020-07-13 19:23 UTC
